//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timesheet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<double> HoursWorked { get; set; }
        public string Project { get; set; }
        public string Task { get; set; }
    }
}
